version: '2.1'
services:
  pymc-repeater:
    build:
      context: .
    network_mode: host
    privileged: true
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
      #- /dev/bus/usb/002:/dev/bus/usb/002
      # SPI DEVICES (Your path may differ)
      - '/dev/spidev0.0'
      - '/dev/gpiochip0'
    # SPI DEVICES PERMISSIONS
    cap_add:
      - SYS_RAWIO
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.supervisor-api: '1'
      io.balena.features.balena-api: '1'
    volumes:
      - config:/etc/pymc-repeater
      - data:/var/lib/pymc_repeater
    group_add:
      - "plugdev"
    restart: always


volumes:
  config:
  data:
